---
splunk:
  role: splunk_standalone
  build_location: https://download.splunk.com/products/splunk/releases/8.0.4.1/linux/splunk-8.0.4.1-ab7a85abaa98-Linux-x86_64.tgz
  apps_location:
    - http://nginx/splunk_app_simple.tgz
    - /tmp/splunk_app_httpexample.tgz
  hec:
    token: abcd1234
  password: helloworld
  disable_popups: true
