---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: splunk/splunk
    command: no-provision
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
provisioner:
  name: ansible
  log: true
scenario:
  name: manual-forwards
verifier:
  name: testinfra
  options:
    junit-xml: ../../../../tests/results/heavy-manual-forwards-results.xml
