---
- name: Set indexer discovery
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/servicesNS/nobody/system/configs/conf-server"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    force_basic_auth: yes
    validate_certs: False
    body:
      name: "indexer_discovery"
      pass4SymmKey: "{{ splunk.idxc.discoveryPass4SymmKey if splunk.idxc.discoveryPass4SymmKey is defined and splunk.idxc.discoveryPass4SymmKey else splunk.idxc.pass4SymmKey }}"
    body_format: "form-urlencoded"
    status_code: 201,409
    timeout: 10
    use_proxy: no
  register: set_indexer_discovery
  changed_when: set_indexer_discovery.status == 201
  no_log: "{{ hide_password }}"

- include_tasks: enable_smartstore.yml
  when: splunk.smartstore

- name: Set the current node as a Splunk indexer cluster master
  command: "{{ splunk.exec }} edit cluster-config -mode master -replication_factor {{ splunk.idxc.replication_factor }} -search_factor {{ splunk.idxc.search_factor }} -secret '{{ splunk.idxc.pass4SymmKey }}' -cluster_label '{{ splunk.idxc.label }}' -auth '{{ splunk.admin_user }}:{{ splunk.password }}'"
  register: task_result
  until: task_result.rc == 0
  changed_when: task_result.rc == 0
  retries: "{{ retry_num }}"
  delay: "{{ retry_delay }}"
  notify:
    - Restart the splunkd service
  become: yes
  become_user: "{{ splunk.user }}"
  no_log: "{{ hide_password }}"

- name: Flush restart handlers
  meta: flush_handlers
