---
# Configure forwarding to indexer cluster master
# See: https://docs.splunk.com/Documentation/Splunk/latest/Indexer/indexerdiscovery
- name: Setup indexer discovery for index-clustering
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/servicesNS/nobody/system/configs/conf-outputs"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "name=indexer_discovery:splunk-indexer&pass4SymmKey={{ splunk.shc.secret }}&master_uri={{ cert_prefix }}://{{ groups['splunk_cluster_master'][0] }}:{{ splunk.svc_port }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 201,409
    timeout: 10
  when: splunk.indexer_cluster
  register: setup_indexer_discovery_stanza
  changed_when: setup_indexer_discovery_stanza.status == 201
  no_log: "{{ hide_password }}"
  notify:
    - Restart the splunkd service

- name: Setup tcpout group for index-clustering
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/servicesNS/nobody/system/configs/conf-outputs"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "name=tcpout:group1&indexerDiscovery=splunk-indexer"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 201,409
    timeout: 10
  when: splunk.indexer_cluster
  register: setup_tcpoutgroup_stanza
  changed_when: setup_tcpoutgroup_stanza.status == 201
  no_log: "{{ hide_password }}"

- name: Setup default tcpout group for index-clustering
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/servicesNS/nobody/system/configs/conf-outputs/tcpout"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "indexAndForward=false&defaultGroup=group1"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 200
    timeout: 10
  when: splunk.indexer_cluster
  register: setup_tcpout_stanza
  changed_when: setup_tcpout_stanza.status == 200
  no_log: "{{ hide_password }}"

# Configure forwarding to indexers directly
# See: https://docs.splunk.com/Documentation/Splunk/latest/Indexer/forwardersdirecttopeers
- include_tasks: ../../../roles/splunk_common/tasks/add_forward_server.yml
  vars:
    role: splunk_indexer
  when: not splunk.indexer_cluster

# Configure forwarding to standalones directly
# See: https://docs.splunk.com/Documentation/Splunk/latest/Indexer/forwardersdirecttopeers
- include_tasks: ../../../roles/splunk_common/tasks/add_forward_server.yml
  vars:
    role: splunk_standalone

# NOTE: If this task is called or used, it will disable all local indexing!
- name: Disable indexing on the current node
  uri:
    url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/servicesNS/nobody/system/configs/conf-outputs"
    method: POST
    user: "{{ splunk.admin_user }}"
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "name=indexAndForward&index=false"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 201,409
    timeout: 10
  register: disable_indexing_stanza
  changed_when: disable_indexing_stanza.status == 201
  no_log: "{{ hide_password }}"
