# added the environment section due to bug:
# https://github.com/ansible/ansible/issues/18979
- name: Import Splunk key
  rpm_key:
    key: https://docs.splunk.com/images/6/6b/SplunkPGPKey.pub
    state: present

- name: Install Splunk (yum)
  yum:
    name: "{{ splunk.build_location }}"
    state: "{{ 'latest' if splunk_upgrade else 'present' }}"
  environment:
    http_proxy: "{{ lookup('env','http_proxy') | default('') }}"
    https_proxy: "{{ lookup('env','https_proxy') | default('') }}"
  register: install_result
  until: install_result is succeeded
  retries: "{{ retry_num }}"
  delay: "{{ retry_delay }}"
  become: yes
  become_user: "{{ privileged_user }}"
