---
- name: Remove old manifest files
  file:
    path: "{{ item.path }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  with_items:
  - "{{ manifests.files }}"
  when: splunk_upgrade | bool

- name: Remove old directories
  file:
    path: "{{ item.path }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  with_items:
    - "{{ splunk.home }}/bin"
    - "{{ splunk.home }}/lib"
    - "{{ splunk.home }}/share"
  when: splunk_upgrade | bool

- name: Install Splunk (Linux)
  unarchive:
    src: "{{ splunk.build_location }}"
    dest: "{{ splunk.opt }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    remote_src: "{{ splunk.build_remote_src }}"
  when: ansible_system is match("Linux")
  register: install_result
  until: install_result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Install Splunk (Windows)
  command: "msiexec /I {{ splunk.build_location }} AGREETOLICENSE=yes SPLUNKUSERNAME={{ splunk.admin_user }} SPLUNKPASSWORD={{ splunk.password }} LAUNCHSPLUNK=0 INSTALLDIR=C:\\\\opt\\\\{{ splunk.tar_dir }} /passive /qn"
  when: ansible_system is match("CYGWIN*|Win32NT")
  register: install_result
  until: install_result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Remove installers
  file:
    dest: "{{ item }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_user: "{{ privileged_user }}"
  with_items:
    - "{{ splunk.build_location }}"
    - "/tmp/splunk.msi"
