---
- include_tasks: get_facts.yml

- include_tasks: change_splunk_directory_owner.yml
  when:
    - ansible_system is match("Linux")
    - splunk_home_ownership_enforcement is defined
    - splunk_home_ownership_enforcement | bool

- include_tasks: update_etc.yml
  register: etc_updated
  when:
    - ansible_system is match("Linux")
    - splunk.build_location is none or splunk.build_location is not match("^(https?|file)://.*")

- include_tasks: stop_splunk.yml
  when:
    - splunk_upgrade | bool or etc_updated is changed

# Below we will either install or upgrade, which at this moment is the same task.
- name: "Install Splunk"
  include_tasks: install_splunk.yml
  when:
    - splunk_install | bool or (first_run | bool and splunk.build_location and splunk.build_location is match("^(https?|file)://.*"))

- name: "Upgrade Splunk"
  include_tasks: install_splunk.yml
  when:
    - not splunk_install
    - not first_run
    - splunk_upgrade | bool
    - splunk.allow_upgrade is defined
    - splunk.allow_upgrade | bool

- name: "Set splunk-launch.conf options"
  include_tasks: set_splunk-launch_options.yml
  when:
    - "'launch_options' in splunk"
    - "splunk['launch_options']|length > 0"

- include_tasks: remove_first_login.yml
  when:
    - first_run | bool

- include_tasks: install_java.yml
  when:
    - java_version is defined
    - first_run | bool

# This needs to be done before any encrypted passkeys are generated
- include_tasks: set_splunk_secret.yml
  when:
    - first_run | bool

- include_tasks: set_user_seed.yml
  when:
    - first_run | bool

- include_tasks: pre_splunk_start_commands.yml
  ignore_errors: true
  when:
    - first_run | bool

- include_tasks: enable_s2s.yml
  when:
    - "('s2s_enable' in splunk and splunk.s2s_enable | bool) or ('s2s' in splunk and 'enable' in splunk.s2s and splunk.s2s.enable | bool)"
    - "('s2s_port' in splunk and splunk.s2s_port) or ('s2s' in splunk and 'port' in splunk.s2s and splunk.s2s.port)"

- include_tasks: enable_service.yml
  when:
    - splunk.enable_service and ansible_system is match("Linux")
    - first_run | bool

- include_tasks: set_http_port.yml
  when:
    - "'http_port' in splunk"
    - splunk.http_port | int != 8000

- include_tasks: set_mgmt_port.yml
  when:
    - "'svc_port' in splunk"
    - splunk.svc_port | int != 8089

- include_tasks: enable_ssl_on_gui.yml
  when:
    - "'http_enableSSL' in splunk and splunk.http_enableSSL is not none"
    - splunk.http_enableSSL | bool
    - first_run | bool

- include_tasks: set_any_generic_config.yml
  when:
    - "'conf' in splunk"
    - first_run | bool

- include_tasks: start_splunk.yml

- include_tasks: set_certificate_prefix.yml

- include_tasks: set_root_endpoint.yml
  when:
    - splunk.root_endpoint is defined
    - splunk.root_endpoint != None
    - first_run | bool

- include_tasks: clean_user_seed.yml
  when:
    - first_run | bool

- include_tasks: add_splunk_license.yml
  when:
    - first_run | bool
