---
- name: "Set stanza {{ stanza_name }}"
  lineinfile:
    path: "{{ conf_directory }}/{{ conf_file }}"
    line: "[{{ stanza_name }}]"
    state: present
    create: yes
    mode: 0660
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  become: yes
  become_user: "{{ splunk.user }}"
  when: stanza_name and not stanza_settings

- name: "Set options in {{ stanza_name }}"
  ini_file:
    path: "{{ conf_directory }}/{{ conf_file }}"
    section: "{{ stanza_name }}"
    option: "{{ stanza_setting.key }}"
    value: "{{ stanza_setting.value }}"
    allow_no_value: True
    state: present
    mode: 0660
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  become: yes
  become_user: "{{ splunk.user }}"
  with_dict: "{{ stanza_settings | default({}) }}"
  loop_control:
    loop_var: stanza_setting
  when: stanza_name and stanza_settings
  no_log: "{{ hide_password }}"
