---
- include_tasks: ../../splunk_common/tasks/enable_forwarding.yml

- include_tasks: ../../splunk_common/tasks/provision_apps.yml
  when: "'apps_location' in splunk and splunk.apps_location"
  vars:
    app_list: "{{ splunk.apps_location }}"

- include_tasks: ../../splunk_common/tasks/provision_apps.yml
  when:
    - "'app_paths_install' in splunk and 'default' in splunk.app_paths_install and splunk.app_paths_install.default"
  vars:
    app_list: "{{ splunk.app_paths_install.default }}"

- name: Enable license master local indexing
  ini_file:
    path: "{{ splunk.home }}/etc/system/local/outputs.conf"
    section: "tcpout"
    option: "indexAndForward"
    value: "true"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  register: lm_local_indexing

# Restart only when Splunk is running and when any of the above have changed
- include_tasks: ../../splunk_common/tasks/trigger_restart.yml
  when: lm_local_indexing is changed

- include_tasks: ../../splunk_common/tasks/check_for_required_restarts.yml
