---
- include_tasks: ../../splunk_common/tasks/set_as_hec_receiver.yml

- include_tasks: ../../splunk_common/tasks/add_splunk_object.yml
  when: splunk.add is defined

- include_tasks: ../../../roles/splunk_common/tasks/set_as_deployment_client.yml
  when:
    - splunk.deployment_server is defined
    - splunk.deployment_server

- include_tasks: ../../splunk_common/tasks/enable_forwarder_monitoring.yml
  when:
    - dmc_forwarder_monitoring is defined
    - dmc_forwarder_monitoring | bool

## Indexer Clustering Scenario
- include_tasks: ../../splunk_common/tasks/peer_cluster_master.yml
  when:
    - splunk_indexer_cluster | bool
    - splunk.multisite_master is not defined
    - splunk.set_search_peers is defined
    - splunk.set_search_peers | bool

## Non Indexer Clustering Scenario
- include_tasks: ../../splunk_common/tasks/peer_indexers.yml
  vars:
    idx: "{{ item }}"
  with_items: "{{ groups['splunk_indexer'] }}"
  when:
    - not splunk_indexer_cluster | bool
    - splunk.multisite_master is not defined
    - splunk.set_search_peers is defined
    - splunk.set_search_peers | bool
    - "'splunk_indexer' in groups"

- include_tasks: ../../splunk_common/tasks/provision_apps.yml
  when:
    - "'apps_location' in splunk and splunk.apps_location"
    - splunk.deployment_server is not defined or not splunk.deployment_server
  vars:
    app_list: "{{ splunk.apps_location }}"

- include_tasks: ../../splunk_common/tasks/provision_apps.yml
  when:
    - "'app_paths_install' in splunk and 'default' in splunk.app_paths_install and splunk.app_paths_install.default"
    - splunk.deployment_server is not defined or not splunk.deployment_server
  vars:
    app_list: "{{ splunk.app_paths_install.default }}"

- include_tasks: ../../../roles/splunk_common/tasks/enable_dfs.yml
  when:
    - "'dfs' in splunk and 'enable' in splunk.dfs and splunk.dfs.enable is not none"
    - splunk.dfs.enable | bool

- include_tasks: ../../splunk_common/tasks/check_for_required_restarts.yml
