---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: splunk-uf-debian10
    image: jgeusebroek/debian10-molecule:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
    volumes:
      - "/opt/splunkforwarder/var"
  - name: splunk-uf-ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
    volumes:
      - "/opt/splunkforwarder/var"
provisioner:
  name: ansible
  env:
    ANSIBLE_HASH_BEHAVIOUR: merge
  inventory:
    links:
      hosts: ../../../../tests/fixtures/molecule-uf-hosts.yml
      group_vars: ./group_vars/
verifier:
  name: testinfra
  options:
    junit-xml: ../../../../tests/results/uf-forwardservers-results.xml
