---
- name: Prepare
  hosts: all
  tasks:
    - name: Check splunk user
      user:
        name: splunk
        password: "*"
        state: present
      become: true

    - name: Setup yum proxy
      lineinfile:
        path: /etc/yum.conf
        regexp: '^proxy='
        line: "proxy={{ lookup('env','http_proxy') }}"
      when:
        - "lookup('env','http_proxy') is defined"
        - "lookup('env','http_proxy')  | length > 0"

    - name: Check packages
      package:
        name:
          - procps
          - curl
          - net-tools
        state: latest
