---
- include_tasks: ../../../roles/splunk_common/tasks/set_as_hec_receiver.yml
  when:
    - first_run
    - not splunk.hec_disabled | bool
    - splunk.hec_token is defined and splunk.hec_token != None

- include_tasks: indexer_clustering.yml
  vars:
    cluster_master_host: "{{ groups['splunk_cluster_master'][0] }}"
  when: splunk.indexer_cluster

- include_tasks: ../../../roles/splunk_common/tasks/set_as_deployment_client.yml
  when:
    - splunk.deployment_server is defined
    - splunk.deployment_server
    - not splunk.indexer_cluster

- include_tasks: ../../../roles/splunk_common/tasks/provision_apps.yml
  when:
    - splunk.apps_location
    - not splunk.indexer_cluster
    - splunk.deployment_server is not defined or not splunk.deployment_server

- include_tasks: setup_multisite.yml
  when:
      - splunk.site is defined
      - splunk.multisite_master is defined

- include_tasks: ../../../roles/splunk_common/tasks/check_for_required_restarts.yml
