---
- include_tasks: search_head_clustering.yml
  when:
    - splunk.search_head_cluster
    - splunk.deployer_included
    - splunk_search_head_captain is defined

## Indexer Clustering Scenario
- include_tasks: peer_cluster_master.yml
  when:
    - splunk.indexer_cluster

## Non Indexer Clustering Scenario
- include_tasks: peer_indexers.yml
  when:
    - not splunk.indexer_cluster

- include_tasks: ../../../roles/splunk_common/tasks/enable_forwarding.yml

- include_tasks: ../../../roles/splunk_common/tasks/set_as_deployment_client.yml
  when:
    - splunk.deployment_server is defined
    - splunk.deployment_server
    - not splunk.search_head_cluster

- include_tasks: ../../../roles/splunk_common/tasks/provision_apps.yml
  when:
    - splunk.apps_location
    - not splunk.search_head_cluster
    - splunk.deployment_server is not defined or not splunk.deployment_server

- include_tasks: setup_multisite.yml
  when:
      - splunk.site is defined
      - splunk.multisite_master is defined

- include_tasks: ../../../roles/splunk_common/tasks/check_for_required_restarts.yml
